[workspace]
members = ["client", "error", "server"]
resolver = "2"

[workspace.package]
authors = ["Thomas Pellissier-Tanon <thomas.pellissier-tanon@helsing.ai>"]
edition = "2021"
version = "0.0.0"
license = "Apache-2.0"
rust-version = "1.79"

[workspace.dependencies]
axum-07 = { package = "axum", version = "0.7", default-features = false }
http = "1"
http-body = "1"
http-body-util = "0.1"
prost = "0.13.2"
prost-reflect = "0.14"
reqwest-012 = { package = "reqwest", version = "0.12", default-features = false }
serde = "1.0.132"
serde_json = "1"
tokio = "1.34"
tonic = { version = "0.12", default-features = false }
tower-service = "0.3.1"
tower = "0.5"
tracing = "0.1.35"
trait-variant = "0.1.2"
twurst-error = { path = "error", version = "0.0.0" }
